name: hson
version: 0.1.0.0

dependencies:
  - base
  - bytestring
  - binary
  - text
  - containers
  - unordered-containers

library:
  source-dirs: src
  exposed-modules:
    - Hson
    - Hson.Parse
    - Hson.Merge
    - Hson.Get

tests:
  hson-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - hson
      - tasty
      - tasty-hunit
      - binary
