name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
      
      - name: Install dependencies
        run: stack setup
      
      - name: Build
        run: stack build --test --no-run-tests
      
      - name: Run tests
        run: stack test
